## Power Query Data Transformation

The following script shows the transformations applied to the FMC dataset to prepare it for the Power BI dashboard:

- Remove unnecessary columns
- Filter rows for "ATSExternal" business type
- Split datetime columns into separate Date and Time columns
- Rename columns for clarity
- Add calculated column for "Delay on carrier arrival"

let
    Source = FMC,
    #"Removed Columns" = Table.RemoveColumns(Source,{"New Tour", "Tour ID"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([Business Types] = "ATSExternal")),
    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows",{"Canceled Reason", "Canceled Override", "Subcarrier", "Truck Filter", "Base Rate", "Currency Unit", "Trailer Id", "Carrier Reference ID", "Business Types", "Freight Type", "Shipper Accounts", "Pull time 2", "Pull time 3", "Pull time 4", "Pull time 5", "Pull time 6", "Pull time 7", "Pull time 8", "Pull time 9", "Pull time 10", "Pull time 11", "Pull time 12", "Pull time 13", "Pull time 14", "Pull time 15", "Pull time 16", "Pull time 17", "Pull time 18", "Pull time 19", "Scheduled Truck Arrival - 3 date", "Scheduled Truck Arrival - 3 time", "Scheduled Truck Arrival - 4 date", "Scheduled Truck Arrival - 4 time", "Scheduled Truck Arrival - 5 date", "Scheduled Truck Arrival - 5 time", "Scheduled Truck Arrival - 6 date", "Scheduled Truck Arrival - 6 time", "Scheduled Truck Arrival - 7 date", "Scheduled Truck Arrival - 7 time", "Scheduled Truck Arrival - 8 date", "Scheduled Truck Arrival - 8 time", "Scheduled Truck Arrival - 9 date", "Scheduled Truck Arrival - 9 time", "Scheduled Truck Arrival - 10 date", "Scheduled Truck Arrival - 10 time", "Scheduled Truck Arrival - 11 date", "Scheduled Truck Arrival - 11 time", "Scheduled Truck Arrival - 12 date", "Scheduled Truck Arrival - 12 time", "Scheduled Truck Arrival - 13 date", "Scheduled Truck Arrival - 13 time", "Scheduled Truck Arrival - 14 date", "Scheduled Truck Arrival - 14 time", "Scheduled Truck Arrival - 15 date", "Scheduled Truck Arrival - 15 time", "Scheduled Truck Arrival - 16 date", "Scheduled Truck Arrival - 16 time", "Scheduled Truck Arrival - 17 date", "Scheduled Truck Arrival - 17 time", "Scheduled Truck Arrival - 18 date", "Scheduled Truck Arrival - 18 time", "Scheduled Truck Arrival - 19 date", "Scheduled Truck Arrival - 19 time", "Scheduled Truck Arrival - 20 date", "Scheduled Truck Arrival - 20 time", "Date Format", "Time Format"}),
    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns1", each true),
    #"Removed Columns2" = Table.RemoveColumns(#"Filtered Rows1",{"Operator ID", "Run Structure ID", "Resource Block ID", "Create Reason", "Rate Type", "Driver Type", "CheckIn time 3", "CheckIn time 4", "CheckIn time 5", "CheckIn time 6", "CheckIn time 7", "CheckIn time 8", "CheckIn time 9", "CheckIn time 10", "CheckIn time 11", "CheckIn time 12", "CheckIn time 13", "CheckIn time 14", "CheckIn time 15", "CheckIn time 16", "CheckIn time 17", "CheckIn time 18", "CheckIn time 19", "CheckIn time 20", "CheckOut time 3", "CheckOut time 4", "CheckOut time 5", "CheckOut time 6", "CheckOut time 7", "CheckOut time 8", "CheckOut time 9", "CheckOut time 10", "CheckOut time 11", "CheckOut time 12", "CheckOut time 13", "CheckOut time 14", "CheckOut time 15", "CheckOut time 16", "CheckOut time 17", "CheckOut time 18", "CheckOut time 19", "CheckOut time 20", "CPT 2", "CPT 3", "CPT 4", "CPT 5", "CPT 6", "CPT 7", "CPT 8", "CPT 9", "CPT 10", "CPT 11", "CPT 12", "CPT 13", "CPT 14", "CPT 15", "CPT 16", "CPT 17", "CPT 18", "CPT 19", "CPT 20", "Total packages", "Loose-Loaded Packages", "Bags", "Carts", "Cases", "Gaylords", "Pallets", "TransShip Containers", "Totes", "ULDs", "Pods", "Packages In Bags", "Packages In Carts", "Packages In Cases", "Packages In Gaylords", "Packages In Pallets", "Packages In TransShip Containers", "Packages In Totes", "Packages In ULDs", "Packages In Pods", "Contract id 1", "Contract id 2", "Contract id 3", "Contract id 4", "Contract id 5", "Contract id 6", "Contract id 7", "Contract id 8", "Contract id 9", "Contract id 10", "Contract id 11", "Contract id 12", "Contract id 13", "Contract id 14", "Contract id 15", "Contract id 16", "Contract id 17", "Contract id 18", "Contract id 19", "Contract id 20", "Contract type 1", "Contract type 2", "Contract type 3", "Contract type 4", "Contract type 5", "Contract type 6", "Contract type 7", "Contract type 8", "Contract type 9", "Contract type 10", "Contract type 11", "Contract type 12", "Contract type 13", "Contract type 14", "Contract type 15", "Contract type 16", "Contract type 17", "Contract type 18", "Contract type 19", "Contract type 20", "Requires Single Container", "Ocean Container SCAC", "Scannable ID", "Trans Mode", "Chassis ID", "EX_AT_TR_CHASSIS_REQUIRED", "EX_AT_TR_CHASSIS_RETURN_REQUIRED", "EX_AT_TR_RAIL_NUMBER", "EX_AT_TR_MBL", "Port Appointment", "Port Pin Code", "Rail Shipment Appointment", "Load Type - 2", "Load Type - 3", "Load Type - 4", "Load Type - 5", "Load Type - 6", "Load Type - 7", "Load Type - 8", "Load Type - 9", "Load Type - 10", "Load Type - 11", "Load Type - 12", "Load Type - 13", "Load Type - 14", "Load Type - 15", "Load Type - 16", "Load Type - 17", "Load Type - 18", "Load Type - 19", "Load Type - 20", "Unload Type - 1", "Unload Type - 3", "Unload Type - 4", "Unload Type - 5", "Unload Type - 6", "Unload Type - 7", "Unload Type - 8", "Unload Type - 9", "Unload Type - 10", "Unload Type - 11", "Unload Type - 12", "Unload Type - 13", "Unload Type - 14", "Unload Type - 15", "Unload Type - 16", "Unload Type - 17", "Unload Type - 18", "Unload Type - 19", "Unload Type - 20"}),
    #"Filtered Rows2" = Table.SelectRows(#"Removed Columns2", each ([CheckIn time 1] <> null)),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows2",{{"Load #", "VRID"}, {"Carrier", "SCAC"}, {"Corresponding CPT", "CPT"}, {"Scheduled Truck Arrival - 1 date", "Scheduled First Dock Arrival date"}, {"Scheduled Truck Arrival - 1 time", "Scheduled First Dock Arrival time"}, {"Trailer Ready Time", "Scheduled First Dock Departure"}, {"Scheduled Truck Arrival - 2 date", "Scheduled Last Dock Arrival Date"}, {"Scheduled Truck Arrival - 2 time", "Scheduled Last Dock Arrival Time"}}),
    #"Split Column by Delimiter" = Table.SplitColumn(Table.TransformColumnTypes(#"Renamed Columns", {{"Scheduled First Dock Departure", type text}}, "en-US"), "Scheduled First Dock Departure", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Scheduled First Dock Departure.1", "Scheduled First Dock Departure.2"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Scheduled First Dock Departure.1", type date}, {"Scheduled First Dock Departure.2", type time}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"Scheduled First Dock Departure.1", "Scheduled First Dock Departure Date"}, {"Scheduled First Dock Departure.2", "Scheduled First Dock Departure Time"}, {"CheckIn time 1", "Actual First Dock Arrival Date"}}),
    #"Split Column by Delimiter1" = Table.SplitColumn(Table.TransformColumnTypes(#"Renamed Columns1", {{"Actual First Dock Arrival Date", type text}}, "en-US"), "Actual First Dock Arrival Date", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Actual First Dock Arrival Date.1", "Actual First Dock Arrival Date.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Actual First Dock Arrival Date.1", type date}, {"Actual First Dock Arrival Date.2", type time}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"Actual First Dock Arrival Date.1", "Actual First Dock Arrival Date"}, {"Actual First Dock Arrival Date.2", "Actual First Dock Arrival Time"}}),
    #"Split Column by Delimiter2" = Table.SplitColumn(Table.TransformColumnTypes(#"Renamed Columns2", {{"CheckIn time 2", type text}}, "en-US"), "CheckIn time 2", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"CheckIn time 2.1", "CheckIn time 2.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter2",{{"CheckIn time 2.1", type date}, {"CheckIn time 2.2", type time}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type2",{{"CheckIn time 2.1", "Actual Last Dock Arrival Date"}, {"CheckIn time 2.2", "Actual Last Dock Arrival Time"}}),
    #"Split Column by Delimiter3" = Table.SplitColumn(Table.TransformColumnTypes(#"Renamed Columns3", {{"CheckOut time 1", type text}}, "en-US"), "CheckOut time 1", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"CheckOut time 1.1", "CheckOut time 1.2"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Split Column by Delimiter3",{{"CheckOut time 1.1", type date}, {"CheckOut time 1.2", type time}}),
    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type3",{{"CheckOut time 1.1", "Actual First Dock Departure Date"}, {"CheckOut time 1.2", "Actual First Dock Departure Time"}}),
    #"Split Column by Delimiter4" = Table.SplitColumn(Table.TransformColumnTypes(#"Renamed Columns4", {{"CheckOut time 2", type text}}, "en-US"), "CheckOut time 2", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"CheckOut time 2.1", "CheckOut time 2.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Delimiter4",{{"CheckOut time 2.1", type date}, {"CheckOut time 2.2", type time}}),
    #"Renamed Columns5" = Table.RenameColumns(#"Changed Type4",{{"CheckOut time 2.1", "Actual Last Dock Departure Date"}, {"CheckOut time 2.2", "Actual Last Dock Departure Time"}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Renamed Columns5",{"CPT 1"}),
    #"Split Column by Delimiter5" = Table.SplitColumn(Table.TransformColumnTypes(#"Removed Columns3", {{"VR Creation Time", type text}}, "en-US"), "VR Creation Time", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"VR Creation Time.1", "VR Creation Time.2"}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Split Column by Delimiter5",{{"VR Creation Time.1", type date}, {"VR Creation Time.2", type time}}),
    #"Renamed Columns6" = Table.RenameColumns(#"Changed Type5",{{"VR Creation Time.1", "VRID Creation Date"}, {"VR Creation Time.2", "VRID Creation Time"}}),
    #"Removed Columns4" = Table.RemoveColumns(#"Renamed Columns6",{"VRID Creation Time", "First Dock Arrival", "First Dock Departure", "Last Dock Arrival"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns4", "Delay on carrier arrival", each [Scheduled First Dock Arrival time]-[Actual First Dock Arrival Time])
in
    #"Added Custom"
